//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetails
    {
        public int bookingDetailID { get; set; }
        public int bookingID { get; set; }
        public int ticketTypeID { get; set; }
        public int quantity { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual TicketTypes TicketTypes { get; set; }
    }
}
