//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetails
    {
        public int cardDetailID { get; set; }
        public int paymentID { get; set; }
        public string cardholderName { get; set; }
        public string cardNumber { get; set; }
        public byte expiryMonth { get; set; }
        public short expiryYear { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
