//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Showtime = new HashSet<Showtime>();
        }
    
        public int MovieID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<decimal> imdb { get; set; }
        public System.DateTime releaseDate { get; set; }
        public string director { get; set; }
        public string genre { get; set; }
        public int duration { get; set; }
        public string movieImg { get; set; }
        public string movieBanner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Showtime> Showtime { get; set; }
    }
}
