//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seatReservations
    {
        public int reservationID { get; set; }
        public int showtimeID { get; set; }
        public int seatID { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Showtime Showtime { get; set; }
    }
}
